### PR TITLE
add some paragraph regarding contributors req.

### PR DESCRIPTION
**Pull request by dewisr**

### CODE REVIEW

**Comment by dewisr** [comment]
Add information

**Comment by dewisr** [comment]
_Nyoba nyoba doang_

**Comment by chrisandoryan** [comment]
Good. But can you create a separate `.md` file for your group (please don't write your group number in the README.md)?

**Comment by dewisr** [comment]
Noted. thank you

**Comment by Prabowo-Bayu** [comment]
add favourite color

**Comment by chrisandoryan** [comment]
Thanks!
Merging your commits now.

**Pull request merged**
